"""
AUTO-GENERATED by Aspora Feedback Loop
Source: Correction CORR-001 (2026-02-12)
Skill: wealth/suggest-allocation
Lesson: Per-market risk profiles can differ from overall profile

This test was automatically created when a user corrected the skill output.
It ensures the same mistake is never repeated.
"""

from deepeval import assert_test
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase


def test_per_market_risk_differentiation():
    """
    CORR-001: User with moderate overall profile but time-sensitive India goal
    should get aggressive India equity allocation, not uniform moderate.
    """
    test_case = LLMTestCase(
        input=(
            "User: USR-NRI-2847, moderate risk profile overall. "
            "Has a Mumbai apartment goal (INR 1.5Cr, deadline 2028-12-31, only 45% funded). "
            "Wants aggressive allocation for India equity to meet this tight deadline. "
            "Keep USD/AED holdings conservative."
        ),
        actual_output="",  # Filled at runtime by skill execution
        expected_output=(
            "India equity allocation should be 70-85% of India-targeted investments. "
            "International holdings should remain at moderate levels (40-60% equity). "
            "Should recommend high-growth India index funds (NIFTY 50, Flexi Cap) "
            "with SIP of INR 65K+ per month to meet 2028 deadline. "
            "USD/AED debt holdings should be preserved as-is."
        ),
    )

    # Metric: Does the output differentiate risk per market?
    per_market_risk = GEval(
        name="Per-Market Risk Differentiation",
        criteria=(
            "The output should show DIFFERENT risk allocations for India equity "
            "vs international holdings. India equity should be aggressive (70%+), "
            "international should be moderate/conservative. The output should NOT "
            "apply a uniform moderate allocation across all markets."
        ),
        evaluation_params=["input", "actual_output", "expected_output"],
        threshold=0.7,
    )

    assert_test(test_case, [per_market_risk])


def test_goal_deadline_drives_allocation():
    """
    CORR-001 follow-up: Time-sensitive goals should increase equity allocation
    for the relevant currency, even if overall profile is moderate.
    """
    test_case = LLMTestCase(
        input=(
            "User has 3 goals: "
            "1. Mumbai apartment (INR 1.5Cr, 2028, 45% funded) — URGENT "
            "2. Children education (USD 200K, 2040, 6% funded) — LONG TERM "
            "3. Retirement (INR 5Cr, 2050, 9% funded) — VERY LONG TERM "
            "Overall risk: moderate. Monthly surplus: AED 13K."
        ),
        actual_output="",  # Filled at runtime
        expected_output=(
            "Goal 1 (urgent, 2028): Aggressive India equity (80%), high SIP amount. "
            "Goal 2 (long term, 2040): Moderate USD allocation, regular DCA. "
            "Goal 3 (very long term, 2050): Can be moderate, compounding has time."
        ),
    )

    goal_awareness = GEval(
        name="Goal-Deadline Awareness",
        criteria=(
            "Allocation aggressiveness should correlate with goal urgency. "
            "The nearest deadline goal should have the highest equity allocation. "
            "The output should explicitly reference each goal's timeline."
        ),
        evaluation_params=["input", "actual_output", "expected_output"],
        threshold=0.7,
    )

    assert_test(test_case, [goal_awareness])
